INSERT INTO Problem1 VALUES(“a”, TRUE, “#3 impliceert dat C de capaciteit is van een voertuig V”);
INSERT INTO Problem1 VALUES(“b”, TRUE, “als je het voertuig hebt kan je zijn capaciteit opzoeken met #3”);
INSERT INTO Problem1 VALUES(“c”, TRUE, “uit #8 blijkt dat F vermeld welke P erbij hoort”);
INSERT INTO Problem1 VALUES(“d”, TRUE, “#7: A weet welke P erbij hoort en #8: F weet welke P erbij hoort”);
INSERT INTO Problem1 VALUES(“e”, TRUE, “#5: G weet welke P erbij hoort en #6: O weet welke P erbij hoort”);
INSERT INTO Problem1 VALUES(“f”, FALSE, “een B kan meerdere V’s hebben”);
INSERT INTO Problem1 VALUES(“g”, FALSE, “er kunnen meerdere B’s zijn voor V”);
INSERT INTO Problem1 VALUES(“h”, TRUE, “als je alle V’s weet weet je alle B’s (#2)”);
INSERT INTO Problem1 VALUES(“i”, TRUE, “als je alle V’s weet weet je alle C’s (#3)”);
INSERT INTO Problem1 VALUES(“j”, TRUE, “h) en i) zijn ook allebei waar.”);
